
name: 🐛 Bug Report
description: Rapportera fel i kodlistorn
title: "[Bug]: "
labels: ["Fel i kodlista"]
body:
  - type: dropdown
    id: kodlist
    attributes:
      label: "Gäller kodlista:"
      options:
        - arkeologiskt objekt
        - naturligt objekt
        - stratigrafisk enhet
        - undersökningsenhet
      multiple: false
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Beskrivning av felet
      description: Förklara felet tydligt och detaljerat.
      placeholder: T.ex. "hirarkierna är fel.."
    validations:
      required: true
